Add support for escaping in DateFormat
Now that we DateFormat can be extended by packages and add custom slots
we need a way to support escaping special characters. For example:

The character 'Z' can be used to indicate Zulu:
```julia
julia> DateTime("2015-07-24T05:38:19.591Z", "yyyy-mm-ddTHH:MM:SS.sssZ")
2015-07-24T05:38:19.591
```

Additionally 'Z' is used by the TimeZones.jl package to indicate a slot:
```julia
julia> using TimeZones

julia> DateTime("2015-07-24T05:38:19.591Z", "yyyy-mm-ddTHH:MM:SS.sssZ")
ERROR: ArgumentError: Ambiguous timezone
```

This commit enables users to escape characters to ignore slots:
```julia
julia> using TimeZones

julia> DateTime("2015-07-24T05:38:19.591Z", "yyyy-mm-ddTHH:MM:SS.sss\\Z")
2015-07-24T05:38:19.591
```